apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: absencesbo-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: absencesbo
    app.kubernetes.io/environment: dev
spec:
  project: absencesbo

  source:
    repoURL: https://github.com/htues/absences_boffice_deployments.git
    targetRevision: main
    path: k8s/helm/helm-chart-app
    helm:
      releaseName: absencesbo
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: absencesbo-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
