global:
  environment: dev

database:
  image:
    repository: hftamayo/pgdevelopment
    tag: "dbdev"

nginx:
  image:
    repository: hftamayo/nginxk8s
    tag: "nginxdev"

  upstreams:
    frontendPort: 80
    backendPort: 8080

healthChecks:
  enabled: false

security:
  enabled: false
