backend:
  image:
    repository: hftamayo/absencesbobe
    # this is a fallback value
    tag: "bedev"
  # Non-sensitive runtime setup overrides
  executionMode: "development"
  frontendOrigins:
    - http://localhost
    - http://localhost:8041
    - https://dev.tamayo.dev/absencesbo