global:
  environment: dev

backend:
  image:
    repository: htues/absencesbobe
    tag: "bedev"
  # Non-sensitive runtime setup overrides
  executionMode: "development"
  frontendOrigins:
    - http://localhost
    - http://localhost:8041
    - https://dev.tamayo.dev/absencesbo

frontend:
  image:
    repository: htues/absencesbofe
    tag: "fedev"

database:
  image:
    repository: htues/pgdevelopment
    tag: "dbdev"

nginx:
  image:
    repository: htues/nginxk8s
    tag: "nginxdev"

  upstreams:
    frontendPort: 80
    backendPort: 8080

healthChecks:
  enabled: false

security:
  enabled: false
