global:
  environment: dev

backend:
  image:
    repository: hftamayo/absencesbobe
    tag: "bedev"
  # Non-sensitive runtime setup overrides
  executionMode: "development"
  frontendOrigins:
    - http://localhost
    - http://localhost:8041
    - https://dev.tamayo.dev/absencesbo

frontend:
  image:
    repository: hftamayo/absencesbofe
    tag: "fedev"

nginx:
  image:
    repository: hftamayo/nginxk8s
    tag: "toolsdev"

  upstreams:
    frontendPort: 80
    backendPort: 8080

healthChecks:
  enabled: false

security:
  enabled: false
